# Generated by Django 6.0.1 on 2026-01-27 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_position', models.CharField(blank=True, help_text="e.g., 'CEO at Company X'", max_length=200)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('testimonial_text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating out of 5')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
