# Generated by Django 6.0.1 on 2026-01-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tech_icons/')),
                ('description', models.TextField(help_text='Why we use this technology - for Tech Insights page')),
            ],
            options={
                'verbose_name': 'Tech Stack Item',
                'verbose_name_plural': 'Tech Stack',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile App'), ('api', 'API/Backend'), ('ecommerce', 'E-Commerce'), ('other', 'Other')], default='web', max_length=20)),
                ('short_description', models.CharField(max_length=300)),
                ('cover_image', models.ImageField(upload_to='projects/')),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('challenge_text', models.TextField(blank=True, help_text='The problem/challenge the client faced')),
                ('solution_text', models.TextField(blank=True, help_text='How we solved it - technical approach')),
                ('results_metrics', models.JSONField(blank=True, help_text='Example: {"load_time": "-40%", "conversions": "+25%"}', null=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('technologies', models.ManyToManyField(related_name='projects', to='projects.techstack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
