# Generated by Django 6.0.1 on 2026-02-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the package'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='features',
            field=models.JSONField(help_text='List of features to display. Structure: [{"text": "Feature Name", "included": true/false}]'),
        ),
    ]
